const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const options = {
    swaggerDefinition: {
      // Like the one described here: https://swagger.io/specification/#infoObject
      info: {
        title: 'Test Generator',
        version: '1.0.0',
        description: 'Test Generator API with autogenerated swagger doc',
      },
      host: 'localhost:8091',
      basePath: '/',
      securityDefinitions:{
            bearerAuth: {
                type: 'apiKey',
                name: 'Authorization',
                scheme: 'Bearer',
                in: 'header'
            }
        },
    },
    //baseUri: 'http://localhost:8091',
    
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./routes/**/*.js'],
  };
  
  const specs = swaggerJsdoc(options);

  module.exports = (app) => {
      app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
    
      app.get('/swagger.json', (req, res) => {
        res.setHeader('Content-Type', 'application/json');
        res.send(specs);
      });

  }